spring:
  datasource:
    url: jdbc:mysql://[my amazon rds endpoint] [MySQL container name]
    username: [my username]
    password: [my password]
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

mybatis:
  type-aliases-package: com.example.demo.mapper.*
  mapper-locations:
    - static/mapper/*

logging:
  level:
    com:
      example:
        demo:
          MemberMapper : TRACE
          XmlMemberMapper : TRACE
