spring:
  datasource:
    url: jdbc:mysql://localhost:3307/postingContainer
    username: sungho
    password: hellodb
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

mybatis:
  type-aliases-package: com.example.demo.mapper.*
  mapper-locations:
    - static/mapper/*

logging:
  level:
    com:
      example:
        demo:
          MemberMapper : TRACE
          XmlMemberMapper : TRACE
